### PR TITLE
London 9 (Lovelace) - Mo Mahboobian - HTML & CSS - Week 2 

### PR DESCRIPTION
**Pull request by momahboobian**
[Live Demo](https://cyf-momahboobian-html-css-challenge.netlify.app/) 

# Your Details

- Your Name: Mo Mahboobian
- Your City: London
- Your Slack Name: momahboobian

# Homework Details

- Module: HTML/CSS
- Week: 2

### CODE REVIEW

**Comment by qingwei91** [comment]
Hi Mo, I had a look, am I right that this is still in progress? I noticed a few things missing:

1. Size is a multiple choices widget, I think it make more sense to be single choice?
2. Delivery date does not seems to comply to the requirement

**Comment by momahboobian** [comment]
> Hi Mo, I had a look, am I right that this is still in progress? I noticed a few things missing:
> 
> 
> 
> 1. Size is a multiple choices widget, I think it make more sense to be single choice?
> 
> 2. Delivery date does not seems to comply to the requirement

Sure, thanks 😊.
I have been advised that I need to use checkbox!
If you look at the one before this commit it was option.

**Comment by qingwei91** [comment]
>  I have been advised that I need to use checkbox!

I see, I didn't know that, that's cool, let's keep it

**Comment by momahboobian** [comment]
> >  I have been advised that I need to use checkbox!
> 
> 
> 
> I see, I didn't know that, that's cool, let's keep it

Thank you so much 😊

**Comment by qingwei91** [comment]
Hi @momahboobian , it seems the live demo link is died, do you know why?

**Comment by momahboobian** [comment]
> Hi @momahboobian , it seems the live demo link is died, do you know why?

Sorry, I have updated it now.

**Pull request closed without merging**
